# Generated by Django 4.0.3 on 2022-05-25 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participates_in',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_member', to=settings.AUTH_USER_MODEL, verbose_name='group_member'),
        ),
        migrations.AddField(
            model_name='methodic_group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_creator', to=settings.AUTH_USER_MODEL, verbose_name='group creator'),
        ),
        migrations.AddField(
            model_name='methodic_group',
            name='invitations',
            field=models.ManyToManyField(blank=True, through='groups.Invites', to=settings.AUTH_USER_MODEL, verbose_name='Invitations'),
        ),
        migrations.AddField(
            model_name='methodic_group',
            name='participates_in',
            field=models.ManyToManyField(related_name='participants', through='groups.Participates_in', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.AddField(
            model_name='invites',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.methodic_group'),
        ),
        migrations.AddField(
            model_name='invites',
            name='invited_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to=settings.AUTH_USER_MODEL, verbose_name='Invited user'),
        ),
    ]
