# Generated by Django 4.0.4 on 2022-06-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methodic_group',
            name='invitation_code',
        ),
        migrations.AddField(
            model_name='methodic_group',
            name='description',
            field=models.TextField(default=None, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
