# Generated by Django 4.0.4 on 2022-06-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_methodic_group_invitation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodic_group',
            name='photo',
            field=models.ImageField(blank=True, upload_to='group_photos/%Y/%m/%d', verbose_name='Group Photo'),
        ),
        migrations.AddField(
            model_name='methodic_group',
            name='short_description',
            field=models.TextField(default=None, max_length=140, verbose_name='Short Description'),
            preserve_default=False,
        ),
    ]
