# Generated by Django 4.0.4 on 2022-06-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_methodic_group_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodic_group',
            name='short_description',
            field=models.TextField(blank=True, max_length=140, verbose_name='Short Description'),
        ),
    ]
