# Generated by Django 4.0.3 on 2022-05-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='Commented at')),
            ],
        ),
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_downloaded', models.DateTimeField(auto_now=True, verbose_name='Downloaded at')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('language', models.CharField(max_length=20, verbose_name='Language')),
                ('student_year', models.IntegerField(verbose_name='Student Year')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is Public?')),
                ('short_description', models.TextField(max_length=140, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('media', models.FileField(blank=True, upload_to='publication_materials/%Y/%m/%d', verbose_name='Media contents of file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited at')),
                ('photo', models.ImageField(blank=True, upload_to='publication_photos/%Y/%m/%d', verbose_name='Publication Photo')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name of subject')),
                ('type', models.CharField(max_length=30, verbose_name='Type of subject')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name', 'type'],
            },
        ),
    ]
