# Generated by Django 4.0.3 on 2022-05-25 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='comments',
            field=models.ManyToManyField(related_name='commentaries', through='news.Comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_id', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='publication',
            name='downloads',
            field=models.ManyToManyField(related_name='teacher_downloads', through='news.Downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.subject'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_downloaded', to='news.publication'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_downloaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_publication', to='news.publication'),
        ),
        migrations.AddField(
            model_name='comments',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_of_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
