# Generated by Django 4.0.4 on 2022-06-12 18:38

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_subject_options_remove_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='media',
            field=models.FileField(blank=True, upload_to='publication_materials/%Y/%m/%d', validators=[news.validators.validate_file_size_25mb], verbose_name='Media contents of file (up to 25MB)'),
        ),
    ]
