# Generated by Django 4.0.4 on 2022-06-03 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommends',
            options={'verbose_name': 'Recommendation', 'verbose_name_plural': 'Recommendations'},
        ),
        migrations.AddField(
            model_name='recommends',
            name='recommendation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profession',
            field=models.CharField(blank=True, default='New Teacher', max_length=150, verbose_name='Profession'),
        ),
    ]
